32 CONSTANT MAX-MOD-DEP

: (CREATE-MODULE-LIST) ( pub-wid "name" -- addr )
  CREATE HERE >R , 0 , MAX-MOD-DEP CELLS ALLOT R>
;

: (MODULE-PUB-WID) ( addr -- pub-wid-addr ) ;

: (MODULE-COUNT) ( addr -- count-addr )
  1 CELLS + ;

: (MODULE-DEP-AT) ( addr i -- dep-addr )
  2 + CELLS + ;

: (MODULE-DEP-ADD) ( other-addr addr -- )
  DUP (MODULE-COUNT) DUP @ 
  SWAP OVER 1+ 
  DUP MAX-MOD-DEP >=
  IF CR
    DUP <# #S #>
    S" MODULE ERR: MODULE[" 2SWAP S+ 
    S" ] DEPENDENCY LIMIT EXCEEDED" S+
    TYPE 
    CR ABORT 
  ENDIF
  SWAP ! (MODULE-DEP-AT) !
;

: (GET-MODULES) ( addr -- ... u )
  DUP (MODULE-PUB-WID) @
  SWAP 1 OVER (MODULE-COUNT)
  @ 0 U+DO
    OVER i (MODULE-DEP-AT) @
    SWAP >R SWAP >R
    RECURSE R> R> ROT +
  LOOP NIP
;

: (GET-MODULE) ( "name" -- addr )
  PARSE-NAME 2DUP FIND-NAME DUP 0= 
  IF 
    CR DROP S" MODULE ERR: [" 2SWAP S+ 
    S" ] NOT FOUND" S+ 
    CR ABORT 
  ENDIF
  >R 2DROP R>
  NAME>INTERPRET
  EXECUTE
;

: BEGIN-MODULE ( "name" -- old-wid pub-wid addr )
  GET-CURRENT WORDLIST
  DUP (CREATE-MODULE-LIST)
  WORDLIST DUP SET-CURRENT
  >R GET-ORDER 1+ R> SWAP SET-ORDER
;

: END-MODULE ( old-wid pub-wid addr -- )
  2DROP SET-CURRENT GET-ORDER 1- NIP SET-ORDER
;

: IMPORT ( "name" -- u )
  GET-ORDER >R
  (GET-MODULE) (GET-MODULES)
  R> OVER >R +
  SET-ORDER R>
;

: END-IMPORT ( u -- )
  >R GET-ORDER
  R@ - R> SWAP
  >R 0 U+DO DROP LOOP
  R> SET-ORDER
;

: EXPORT ( pub-wid addr "name" -- pub-wid addr )
  PARSE-NAME 2DUP
  S" BEGIN-MODULE" str= IF
    2DROP GET-CURRENT WORDLIST DUP
    (CREATE-MODULE-LIST) 
    OVER SET-CURRENT EXIT
  ENDIF
  2DUP S" IMPORT" str= IF
    2DROP (GET-MODULE) OVER
    (MODULE-DEP-ADD) EXIT
  ENDIF
  2DUP S" :" str= IF
    2DROP GET-CURRENT >R
    OVER SET-CURRENT
    S" : " [CHAR] ; PARSE S+ S" ;" S+
    EVALUATE R> SET-CURRENT EXIT
  ENDIF
  S" MODULE ERR: [EXPORT " 2SWAP S+ 
  S" ] INVALID SYNTAX" S+ 
  CR ABORT
;