: BEGIN-MODULE ( "name" -- old-wid )
  GET-CURRENT
  WORDLIST DUP CONSTANT
  DUP SET-CURRENT >R
  GET-ORDER 1+ R> SWAP SET-ORDER
;

: BEGIN-EXPORT-MODULE

;

: END-MODULE ( old-wid -- )
  SET-CURRENT
  GET-ORDER 1- NIP SET-ORDER
;
